### PR TITLE
MVP Milestone

### LINKED ISSUE #53: MVP Target October 31st
Current status 29th September 2020:

1. CA
2. OAuth2 (this is providing an HTTP integration)
3. Cleanup + NAT fixing
4. Polykey Desktop GUI
5. Integration into Ouroboros experiment
6. All the rest of existing issues that's labelled with the MVP milestone on the project board

Target is 31st October 2020.

### LINKED ISSUE #54: Migration to Vue 3 and Vuex 4 (supported by TypeScript-Demo-SPA)
Currently PolyKey is using vue 2, but a... couple of weeks ago, vue 3 was released and there's a few changes that need to be made. 

I'm not sure how much of the frontend work I've done with vue 3 will translate to the electron based work that is PolyKey, so I'll just cover the differences I can see as of right now. Also, it seems like you're using `vuex-class` which doesn't seem to support vue 3, so there's a lot of differences.

The typescript-demo-spa should be using the composition API which provides reactive states within components and helpful hooks. https://v3.vuejs.org/api/composition-api.html#setup introduces the idea. 

Vuex 4 also brings some changes to the table, and I'm still figuring out some parts but I'll go over what I know. 
Mutations, Actions, Getters and State are all now strongly typed in typescript, and it doesn't seem like vuex-module-decorators is supporting Vuex 4 yet. https://dev.to/3vilarthas/vuex-typescript-m4j and https://github.com/vuejs/vuex/issues/994 explains the reasoning behind this, and why the `$store` is now manually declared. It also has an example of how to set it all up. As expected the store can be called from the `vue` components using a `useStore` hook. The article shows this more in depth.
The idea behind Mutations, Actions, Getters seems to remain the same but they are just defined in a much more verbose way without the decorators, so all the functionality *should* be able to remain. That said, I haven't yet looked into how to get namespaced modules in Vuex 4 though it seems like there is a way. 

I can also see that you're using webpack but it seems to be an electron thing and I can't see any similarities to the webpack I've been using so there isn't much to to say there.

Vue dependencies that have been updated:
*  `"vue": "^2.6.11"` -> `"vue": 3.0.0`
* `"vuex": "^3.4.0"` -> `"vuex": 4.0.0-beta.4`

Not yet updated for vue 3:
* `vuex-class`
* `vuex-module-decorators`
* `vue-property-decorator` Though support is planned for this https://github.com/kaorun343/vue-property-decorator/issues/294
* `vue-class-component`
* `vue-styled-components` 

@CMCDragonkai  @robert-cronin

### PR DESCRIPTION
**Pull request by robert-cronin**
Changes:
1. using vue3 and vuex4
2. using electron-builder and webpack-cli for building

Fixes #53 
Fixes #54

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
This migration is only migrating the vue components.

But later by bringing in some other changes, this will also make the application build for NixOS and other platforms.

**Comment by CMCDragonkai** [comment]
This needs to pull in changes from `cva_test` and `temp_mvp`.

**Comment by robert-cronin** [comment]
cva_test brings in specific changes from vue3 and temp_mvp is more for the nixos builder specific stuff

**Comment by CMCDragonkai** [comment]
Aiming for this PR to be merged by the end of this week.

**Comment by CMCDragonkai** [comment]
Current status:

1. Can build on Mac - but the build doesn't have any components
2. Cannot build on NixOS
3. Need to successful build for NixOS plus components that are migrated

**Comment by CMCDragonkai** [comment]
@gideonairex if this PR can be merged within this week with working builds and ported-over components, then we can start working on drafting the UI.

Please start writing comments here too instead of inside the issues. The issues are for general discussion about the task. Once the task is started, write comments into the PR instead.

**Comment by gideonairex** [comment]
Current Status:

1. Build is working in NixOS

**Comment by robert-cronin** [comment]
temp_mvp and cva_test branches have both had their changes copied over to mvp branch

**Comment by gideonairex** [comment]
Current status:

1. Updated the UI to use Balm UI for now to make it easier to add the UI components
2. Updated the webpack to handle node_modules css

**Comment by gideonairex** [comment]
Current status:

1. Make the vue-router work.
2. Use useRouter for routing
3. Add BalmUI fonts
4. Use BalmUI components still in development

**Comment by gideonairex** [comment]
Current status:

1. Migrated to using vuex4
2. Migrated components to use vue3
3. Partial migration of Balm UI

Need discussion:
1. Currently upon checking the vuex4 we are now using `useStore` but have not found a way to make this elegant. Let me know what you think about this [useModule](https://github.com/MatrixAI/PolyKey/blob/mvp/src/renderer/App.vue#L32). This is a substitute for using the decorators. @robert-cronin @CMCDragonkai 


UI progress:
Screen Shot 2020-10-28 at 3 47 25 PM
Screen Shot 2020-10-28 at 3 47 31 PM
Screen Shot 2020-10-28 at 3 47 36 PM

**Comment by gideonairex** [comment]
Current status:

1. Migrated the functions to the new vuex4 stores
2. Succesfully run the PolyKeyClient

Todo:
1. Integrate the PolyKeyClient to the new vuex4 stores

**Comment by CMCDragonkai** [comment]
Are we merging this?

**Comment by CMCDragonkai** [comment]
I'm not able to answer the question about useStore vs useModule. Can you explain further? In the interests of time, make your best judgement and proceed. @gideonairex

**Comment by robert-cronin** [comment]
I think we can merge this on Monday, there were some issues with nix not being able download some npm packages, but I suspect that was just an issue with my connection. Once we resolve that issue and polykey is installable on our machines then we can go ahead and merge I think :+1:

**Comment by CMCDragonkai** [comment]
The nix and npm integration is being addressed in the TypeScript-Demo-Lib but we hit some issues with node2nix.

On 1 November 2020 12:51:54 am AEDT, Robbie Cronin <notifications@github.com> wrote:
>I think we can merge this on Monday, there were some issues with nix
>not being able download some npm packages, but I suspect that was just
>an issue with my connection. Once we resolve that issue and polykey is
>installable on our machines then we can go ahead and merge I think :+1:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/PolyKey/pull/55#issuecomment-719937015

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robert-cronin** [comment]
The build is working now, but there are a few issues after installation has finished, namely:

1. polykey-gui and pk commands don't work after installation (the only thing that works atm is running from the start menu)
2. when pk-gui comes up, there is an error saying:
```
Error: Image could not be created from ..../static/logo.png
```
3. tray icon doesn't work in the installed app (probably has something to do with not being able to create the image from the logo.png above)

**Comment by gideonairex** [comment]
Added [tailwind](https://tailwindcss.com/) so that we can easily create our composable components. 

Pushed sample usage on App.vue. 

On `tailwind.config.js` this file will control our own theme. 
Added `postcss-loader` so that tailwind will compile on webpack build.

**Pull request merged**
