### PR TITLE
Add Electron

### LINKED ISSUE #5: Polykey GUI Framework
We want Polykey frontends deployable on multiple platforms.

This is no longer updated, but demonstrates a simple application with the same codebase targeting mobile, web and desktop platforms: https://github.com/benoitvallon/react-native-nw-react-calculator

### LINKED ISSUE #16: Deployment - NPM
For the Polykey CLI prototype, we want this to be NPM installable. So NPM is our first deployment target. Later we'll add more deployment paths, and this will need to be automated into our CI/CD to distribute these packages automatically.

### LINKED ISSUE #19: Installation Procedure
Upon installation the command `polykey` will be made available to the `PATH`. This allows them to run the `polykey` command on their terminal.

Upon the initial run of `polykey`:

1. Optional installation of the short alias `pk` (alias is really just something that can be added to the shell or as an additional symlink).
2. Specification of the location of keynode state.
3. Creation of the keynode public and private keypair.
4. Detection/installation of the agent (the agent may need to be installed alternatively in some OSes like Linux)

### LINKED ISSUE #42: Redux vs. Vuex for use in Vue.js
Vuex is a state management library similar to Redux and this issue is for documenting the differences in the two and deciding which is the best for the PolyKey app.

[Here](https://www.codementor.io/@petarvukasinovic/redux-vs-vuex-for-state-management-in-vue-js-n10yd7g2f) are some notes along this line from [codementor.io](codementor.io)

The main difference is that Vuex mutates the state as opposed to Redux making it immutable. From the vuejs [documentation](https://vuejs.org/v2/guide/state-management.html), Redux can be used with Vue.js just fine via a package [redux-vue](https://classic.yarnpkg.com/en/package/redux-vue). The question is what advantage is there to adopting Vuex?

It also looks like Vuex optimises for the Vuejs components and is claimed to be a little more efficient than Redux within Vuejs. I will have further information after I try an experiment with Vuex within the PolyKey Electron app.

### LINKED ISSUE #45: Automatic Deployment with CI/CD
As per #16, we need to figure out how to automatically deploy `js-polykey` and `PolyKey` repositories as a part of our gitlab CI/CD pipeline. We can add it [manual deployments](https://docs.gitlab.com/ee/ci/environments/#configuring-manual-deployments) with `.gitlab-ci.yml`. This would expose a "play" button with a deploy option after the pipeline is successful.

### PR DESCRIPTION
**Pull request by robert-cronin**
This is the PR to add electron to the project, its quite a big change so I think its best if we just keep it as adding electron (adding nativescript and all the code for polykey can come in later PRs)

Fixes #5 
Fixes #16 
Fixes #19 
Fixes #42 
Fixes #45

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Do you want to merge this into master, so this is the main branch to work from?

**Comment by robert-cronin** [comment]
sure, I will take a look at master branch and see if there is anything we should save. Then we can merge into master. Also, I guess the `add-nativescript` branch is unnecessary now, I will remove it in lieu of the repo on gitlab

**Comment by robert-cronin** [comment]
in light of the passing pipeline, I will merge this now

**Comment by CMCDragonkai** [comment]
Awesome!

**Pull request merged**
